name: balloon_puzzle_factory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1
  flutter_svg: ^2.0.17
  loading_animation_widget: ^1.3.0
  just_audio: ^0.9.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/json/
  fonts:
    - family: Alfa Slab One
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf
          weight: 400
    - family: Atop
      fonts:
        - asset: assets/fonts/Atop.ttf
          weight: 400
    - family: Shadows Into Light
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf
          weight: 400